export const SEARCH_ARTISTS_REQUEST = 'SEARCH_ARTISTS_REQUEST';
export const SEARCH_ARTISTS_REQUEST_SUCCESS = "SEARCH_ARTISTS_REQUEST_SUCCESS";
export const SEARCH_ARTISTS_REQUEST_FAILURE = "SEARCH_ARTISTS_REQUEST_FAILURE";
